apiVersion: v1
clusters:
- cluster:
    server: https://c114-e.us-south.containers.cloud.ibm.com:32181
  name: cp4i-update-ann-cluster/c4fd809d01rkchhab1mg
- cluster:
    server: https://c114-e.us-south.containers.cloud.ibm.com:32181
  name: c114-e-us-south-containers-cloud-ibm-com:32181
contexts:
- context:
    cluster: cp4i-update-ann-cluster/c4fd809d01rkchhab1mg
    namespace: default
    user: ann.umberhocker@ibm.com/db138d65ce6a4c7889fd6b359053a0a6
  name: cp4i-update-ann-cluster/c4fd809d01rkchhab1mg
- context:
    cluster: c114-e-us-south-containers-cloud-ibm-com:32181
    namespace: default
    user: IAM#ann.umberhocker@ibm.com/c114-e-us-south-containers-cloud-ibm-com:32181
  name: default/c114-e-us-south-containers-cloud-ibm-com:32181/IAM#ann.umberhocker@ibm.com
current-context: default/c114-e-us-south-containers-cloud-ibm-com:32181/IAM#ann.umberhocker@ibm.com
kind: Config
preferences: {}
users:
- name: IAM#ann.umberhocker@ibm.com/c114-e-us-south-containers-cloud-ibm-com:32181
  user:
    token: sha256~GMuq0_gngb3e72oB17SDpZXyRn_m87w-38ckt-slXmI
