apiVersion: v1
clusters:
- cluster:
    server: https://c109-e.us-east.containers.cloud.ibm.com:31342
  name: ann-test-classic-cluster/c4e3k9hw094vmblbfcd0
- cluster:
    server: https://c109-e.us-east.containers.cloud.ibm.com:31342
  name: c109-e-us-east-containers-cloud-ibm-com:31342
contexts:
- context:
    cluster: ann-test-classic-cluster/c4e3k9hw094vmblbfcd0
    namespace: default
    user: ann.umberhocker@ibm.com/db138d65ce6a4c7889fd6b359053a0a6
  name: ann-test-classic-cluster/c4e3k9hw094vmblbfcd0
- context:
    cluster: c109-e-us-east-containers-cloud-ibm-com:31342
    namespace: default
    user: IAM#ann.umberhocker@ibm.com/c109-e-us-east-containers-cloud-ibm-com:31342
  name: default/c109-e-us-east-containers-cloud-ibm-com:31342/IAM#ann.umberhocker@ibm.com
current-context: default/c109-e-us-east-containers-cloud-ibm-com:31342/IAM#ann.umberhocker@ibm.com
kind: Config
preferences: {}
users:
- name: IAM#ann.umberhocker@ibm.com/c109-e-us-east-containers-cloud-ibm-com:31342
  user:
    token: sha256~5VIJFMglmych0-BWh-AEPMbO4x-X7Et5DXxfmU9Dw00
